name: Build Sphinx docs

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pages: read

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    container: metaseqopt.azurecr.io/metaseq-opt-singularity:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v3

      - name: Build Metaseq and Install dependencies
        run: |
          conda run -n ptca pip install --user -e ".[dev,docs]"
          conda run -n ptca python setup.py install --user

      - name: Build Sphinx docs using Make
        run: |
          cd docs
          make html

      - name: Upload Sphinx HTML as Action Artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: docs/build/html
